echo ""
echo "这些进程是 agent 正在运行的进程，注意检查是否存在僵尸进程"
ps aux | grep "python" | grep "workspaces/task_0/code"
ps aux | grep "python" | grep "search_dataset_tools"

echo ""
echo "这些进程是正在运行实验的主进程"
ps aux | grep "python run.py --agent ml_master_datatree" | grep -v "grep"
echo ""
echo "选择对应的 task 的 PID，然后输入 kill <PID>"