rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/smartphone-decimeter-2022 ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/spaceship-titanic ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/spooky-author-identification ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/stanford-covid-vaccine ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/statoil-iceberg-classifier-challenge ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tabular-playground-series-dec-2021 ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tabular-playground-series-may-2022 ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tensorflow-speech-recognition-challenge ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tensorflow2-question-answering ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/text-normalization-challenge-english-language ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/text-normalization-challenge-russian-language ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tgs-salt-identification-challenge ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/the-icml-2013-whale-challenge-right-whale-redux ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/tweet-sentiment-extraction ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/us-patent-phrase-to-phrase-matching ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/uw-madison-gi-tract-image-segmentation ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/ventilator-pressure-prediction ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/vesuvius-challenge-ink-detection ${DATA_ROOT}/
# rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/vinbigdata-chest-xray-abnormalities-detection ${DATA_ROOT}/
rsync -avzP --info=progress2 -e "ssh" xiyuan@dp_gpu_4090_1:/data/exp_data/whale-categorization-playground ${DATA_ROOT}/
